import { type SiteConfig } from "@/lib/schema/site-config"

export const SEED_CONFIG: SiteConfig = {
  version: 1,
  metadata: {
    title: "Schreinerei Meyer — Ihr Schreiner in München",
    description: "Qualitäts-Schreinerei für Küchen, Treppen und Möbel. Seit 1987 in München. Jetzt kostenloses Angebot anfragen.",
    favicon_emoji: "🪵",
  },
  seo: {
    local_business: {
      schema_type: "HomeAndConstructionBusiness",
      name:    "Schreinerei Meyer GmbH & Co. KG",
      address: "Pasingstraße 42",
      city:    "München",
      zip:     "81241",
      country: "DE",
      phone:   "+49 89 12345678",
      email:   "kontakt@meyer-schreinerei.de",
      price_range: "€€",
      hours: [
        { days: "Mo–Fr", open: "08:00", close: "17:00" },
        { days: "Sa",    open: "09:00", close: "13:00" },
      ],
    },
  },
  navigation: {
    logo_text: "Meyer Schreinerei",
    links: [
      { label: "Leistungen",   href: "#services" },
      { label: "Referenzen",   href: "#case-studies" },
      { label: "Team",         href: "#team" },
      { label: "FAQ",          href: "#faq" },
      { label: "Kontakt",      href: "#contact" },
    ],
    cta: { label: "Anfrage stellen", href: "#contact" },
  },
  theme: {
    style: "craft",
    colors: {
      primary:    "#7c4a1e",
      secondary:  "#a86a2d",
      accent:     "#fdf6ee",
      background: "#fafaf8",
      text:       "#2c1a0e",
      muted:      "#8a6a4a",
    },
    typography: {
      headingFont: "playfair",
      bodyFont:    "lato",
      scale:       "default",
    },
    radius: "sm",
    shadow: "sm",
  },
  sections: [
    {
      id:      "00000000-0000-0000-0000-000000000001",
      type:    "hero",
      variant: "split",
      order:   0,
      enabled: true,
      content: {
        headline:    "Holz mit Herz — Schreinerei seit 1987",
        subheadline: "Von der Maßküche bis zur Treppe: Wir fertigen alles, was Ihr Zuhause braucht. Persönlich, präzise, aus München.",
        badge: "Familienbetrieb · 35+ Jahre",
        cta_primary:   { label: "Kostenloses Angebot", href: "#contact" },
        cta_secondary: { label: "Referenzen ansehen",  href: "#case-studies" },
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000002",
      type:    "logos",
      variant: "strip",
      order:   1,
      enabled: true,
      content: {
        headline: "Zertifiziert & ausgezeichnet",
        logos: [
          { name: "Meisterbetrieb", image_url: "https://placehold.co/120x40/fdf6ee/7c4a1e?text=Meister" },
          { name: "Holz+",          image_url: "https://placehold.co/120x40/fdf6ee/7c4a1e?text=Holz%2B" },
          { name: "Bayern Design",  image_url: "https://placehold.co/120x40/fdf6ee/7c4a1e?text=Design" },
          { name: "FSC Zertifiziert", image_url: "https://placehold.co/120x40/fdf6ee/7c4a1e?text=FSC" },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000003",
      type:    "services",
      variant: "cards",
      order:   2,
      enabled: true,
      content: {
        headline:    "Unsere Leistungen",
        subheadline: "Jedes Stück entsteht in unserer Werkstatt in München-Pasing.",
        items: [
          { icon: "star",    title: "Maßküchen",   description: "Individuell geplant, bis ins letzte Detail. Vom Entwurf bis zur Montage." },
          { icon: "settings",title: "Treppen",     description: "Massivholz oder Kombination: Wir bauen Treppen, die halten — und die man sehen will." },
          { icon: "leaf",    title: "Möbel",       description: "Regale, Schränke, Sideboards — alles genau für Ihren Raum." },
          { icon: "shield",  title: "Restaurierung",description: "Alte Stücke neu beleben. Mit dem gleichen Respekt wie Neuanfertigungen." },
          { icon: "home",    title: "Montage",     description: "Pünktlich, sauber, fertig. Unser Team kümmert sich um alles." },
          { icon: "check",   title: "Beratung",    description: "Kostenlose Erstberatung vor Ort. Wir hören zu, bevor ein Span fällt." },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000004",
      type:    "stats",
      variant: "grid",
      order:   3,
      enabled: true,
      content: {
        items: [
          { value: "35+",    label: "Jahre Erfahrung" },
          { value: "1.200+", label: "Projekte abgeschlossen" },
          { value: "12",     label: "Fachkräfte im Team" },
          { value: "98 %",   label: "Weiterempfehlungsrate" },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000005",
      type:    "case-studies",
      variant: "cards",
      order:   4,
      enabled: true,
      content: {
        headline: "Ausgewählte Projekte",
        items: [
          {
            title:       "Maßküche Bogenhausen",
            client:      "Familie Richter",
            description: "Offene Wohnküche in Eiche natur, 9 Meter lang, mit integrierter Bar und Kücheninsel.",
            tags:        ["Küche", "Eiche", "Insel"],
            image_url:   "https://placehold.co/600x400/fdf6ee/7c4a1e?text=K%C3%BCche",
          },
          {
            title:       "Treppenrenovierung Schwabing",
            client:      "Altbau 1920er",
            description: "Komplette Erneuerung einer Kastenwangentreppe. Neue Stufen, Geländer, Handlauf in Nuss.",
            tags:        ["Treppe", "Nussbaum", "Renovierung"],
            image_url:   "https://placehold.co/600x400/fdf6ee/7c4a1e?text=Treppe",
          },
          {
            title:       "Bibliothek Grünwald",
            client:      "Villa Bergmann",
            description: "Raumhohe Bibliothek mit Rollleiter, 4 × 3,5 m, in Kirschbaum.",
            tags:        ["Bibliothek", "Kirschbaum", "Maßarbeit"],
            image_url:   "https://placehold.co/600x400/fdf6ee/7c4a1e?text=Bibliothek",
          },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000006",
      type:    "testimonials",
      variant: "cards",
      order:   5,
      enabled: true,
      content: {
        headline: "Was unsere Kunden sagen",
        items: [
          { quote: "Die Küche ist ein Traum. Herr Meyer hat jeden Wunsch umgesetzt — und das zu einem fairen Preis.", author: "Sabine K.", role: "München-Schwabing", rating: 5 },
          { quote: "Unsere alte Eichentreppe hat eine zweite Jugend bekommen. Handwerk auf höchstem Niveau.", author: "Thomas R.", role: "München-Bogenhausen", rating: 5 },
          { quote: "Super Kommunikation, termingerecht fertig, kein Staub in der Wohnung. Perfekt.", author: "Julia M.", role: "Grünwald", rating: 5 },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000007",
      type:    "team",
      variant: "grid",
      order:   6,
      enabled: true,
      content: {
        headline:    "Unser Team",
        subheadline: "Zwölf Fachkräfte mit einer Leidenschaft: Holz.",
        members: [
          { name: "Hans Meyer",   role: "Geschäftsführer & Schreinermeister", bio: "Seit 1987 im Betrieb. Gründer der zweiten Generation." },
          { name: "Laura Meyer",  role: "Planung & Design",                  bio: "Innenarchitekturstudium, spezialisiert auf Maßküchen." },
          { name: "Stefan Wolf",  role: "Werkstattleiter",                   bio: "25 Jahre Erfahrung in der Holzbearbeitung." },
          { name: "Anna Bauer",   role: "Kundenberatung",                    bio: "Ihre Ansprechpartnerin für alle Anfragen." },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000008",
      type:    "process",
      variant: "steps",
      order:   7,
      enabled: true,
      content: {
        headline:    "So läuft ein Projekt ab",
        subheadline: "Von der ersten Idee bis zur fertigen Montage — transparent und planbar.",
        items: [
          { step: "1", title: "Erstgespräch",  description: "Kostenlose Beratung vor Ort oder per Video. Wir hören zu und verstehen Ihren Bedarf." },
          { step: "2", title: "Planung",       description: "3D-Visualisierung und Materialauswahl. Sie sehen Ihr Projekt, bevor es entsteht." },
          { step: "3", title: "Angebot",       description: "Transparentes Festpreisangebot ohne versteckte Kosten. Unterschrift genügt." },
          { step: "4", title: "Fertigung",     description: "Alles entsteht in unserer Werkstatt in München-Pasing. Qualitätskontrolle inklusive." },
          { step: "5", title: "Montage",       description: "Pünktliche Lieferung und saubere Montage durch unser eigenes Team." },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000009",
      type:    "faq",
      variant: "accordion",
      order:   8,
      enabled: true,
      content: {
        headline: "Häufige Fragen",
        items: [
          { question: "Wie lange dauert ein Küchenprojekt?",            answer: "Von der Bestellung bis zur Montage rechnen Sie mit 6–10 Wochen. In der Hochsaison (Herbst) kann es etwas länger dauern." },
          { question: "Kommen Sie auch außerhalb Münchens?",            answer: "Ja, wir arbeiten im Umkreis von 50 km um München. Für größere Projekte auch darüber hinaus." },
          { question: "Was kostet eine Maßküche?",                      answer: "Das hängt stark von Material und Größe ab. Einfache Küchen starten bei ca. 8.000 €, hochwertige Projekte können 30.000 € und mehr kosten." },
          { question: "Bieten Sie eine Garantie?",                      answer: "Ja, 5 Jahre Garantie auf alle Neuanfertigungen und 2 Jahre auf Restaurierungen." },
          { question: "Kann ich das Material selbst aussuchen?",        answer: "Natürlich. Wir beraten Sie bei der Auswahl und zeigen Ihnen alle Optionen in unserer Musterausstellung." },
        ],
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000010",
      type:    "contact-form",
      variant: "split",
      order:   9,
      enabled: true,
      content: {
        headline:        "Projekt anfragen",
        subheadline:     "Beschreiben Sie kurz Ihr Vorhaben — wir melden uns innerhalb von 24 Stunden.",
        submit_label:    "Anfrage senden",
        success_message: "Vielen Dank! Wir melden uns innerhalb von 24 Stunden.",
        submit_to_email: "kontakt@meyer-schreinerei.de",
        show_phone:      true,
      },
    },
    {
      id:      "00000000-0000-0000-0000-000000000011",
      type:    "footer",
      variant: "minimal",
      order:   10,
      enabled: true,
      content: {
        logo_text: "Meyer Schreinerei",
        tagline:   "Holz mit Herz seit 1987",
        copyright: "© 2025 Schreinerei Meyer GmbH & Co. KG",
        legal_links: [
          { label: "Impressum",   href: "/impressum" },
          { label: "Datenschutz", href: "/datenschutz" },
        ],
      },
    },
  ],
}
